language: ruby
rvm:
- 2.0.0
- 1.9.3
before_script: cat Berksfile; bundle exec berks install; bundle exec berks list -d
script: bundle exec strainer test --except kitchen
notifications:
  slack:
    secure: TIZFCcm+FcFBB6IoEBv2174qwXe1SxVsGpkMe6eZjccVwmgRt2ik8To03Orpjy/2VOztuqJdDqmHOucbmoL/67W2rnAHjVk85dlGGv60Xqf4F+oSfmc0igESocfZLbv0yhD2SBDIt/RGRqQyGEW1YmNsk7QiFx0HqnXpn0aycaA=
